### ISSUE TITLE
Strings in frontend iframe form are not being translated

### ISSUE THREAD

**Issue by fidoboy** [impress-org/givewp#7035]
In v3-rc8 the frontend form multi-step is displaying english strings untranslated but others are well.

**Comment by JoshuaHungDinh** [comment]
@fidoboy, Thank you for reporting this!

Our team is now aware of this matter, and it will be investigated by a developer. We'll keep you updated on the progress. If you encounter any further issues or have additional information to share, please don't hesitate to let us know. Your feedback is appreciated.

**Comment by JasonTheAdams** [comment]
Hi @fidoboy!

Just wanted to give you a heads up that we just merged https://github.com/impress-org/givewp/pull/7039

This will be included in the upcoming 3.0 release!

**Comment by fidoboy** [comment]
Hi @JasonTheAdams I've just downloaded the new rc9 and strings are still not being translated.

**Comment by glaubersilva** [comment]
@fidoboy Can you provide some samples of strings not being translated?

**Comment by fidoboy** [comment]
> Hi @fidoboy
> 
> Can you provide some samples of strings not being translated?

In multi step iframe the words: raised, goal, secure transaction, amount, etc. Many of them.

**Comment by fidoboy** [comment]
> Hi @fidoboy
> 
> Can you provide some samples of strings not being translated?

@glaubersilva 
This is captured today, using GiveWP 3.0 final version. As you can notice there are untranslated strings in multi step form in frontend.

![Captura1](https://github.com/impress-org/givewp/assets/143312/2b17f638-71ae-4e72-956a-2d1b347966ea)

![Captura2](https://github.com/impress-org/givewp/assets/143312/767d872c-bb96-4c02-8245-0cbe9028ab43)

![Captura3](https://github.com/impress-org/givewp/assets/143312/2f615d3a-92e2-4f19-a1cc-41ba089ef142)

**Comment by glaubersilva** [comment]
@fidoboy After investigating it further, we realized that the new strings are present in the source file (`give.pot`) shipped with the plugin. However, the translation files (`*.po`) from wp.org that you can download from the WordPress updates page are not getting updated with these new strings. We have a developer working on it, but it can take time to figure out why these strings aren't synced.

In this means time, you can download the [Loco plugin](https://br.wordpress.org/plugins/loco-translate/) and use the sync feature to add the new strings from the source file (`give.pot`) in the translation file (`*.po`) of your language - check the attached screenshots for visual references about how to do it. 

After adding/syncing the new strings to your language file (`*.po`)  you can use the Loco translate UI to translate the new strings. Let me know if you have any more questions. =) 

![sync-1](https://github.com/impress-org/givewp/assets/16308864/29e52ff0-c384-4147-8340-8325af7c3d31)

![sync-2](https://github.com/impress-org/givewp/assets/16308864/cdafd7d6-312d-45f3-9f36-a70baf5a421e)

**Comment by fidoboy** [comment]
> @fidoboy After investigating it further, we realized that the new strings are present in the source file (`give.pot`) shipped with the plugin. However, the translation files (`*.po`) from wp.org that you can download from the WordPress updates page are not getting updated with these new strings. We have a developer working on it, but it can take time to figure out why these strings aren't synced.
> 
> In this means time, you can download the [Loco Translate plugin](https://br.wordpress.org/plugins/loco-translate/) and use the sync feature to add the new strings from the source file (`give.pot`) in the translation file (`*.po`) of your language - check the attached screenshots for visual references about how to do it.
> 
> After adding/syncing the new strings to your language file (`*.po`) you can use the Loco translate UI to translate the new strings. Let me know if you have any more questions. =)
> 
> ![sync-1](https://user-images.githubusercontent.com/16308864/276394121-29e52ff0-c384-4147-8340-8325af7c3d31.png)
> 
> ![sync-2](https://user-images.githubusercontent.com/16308864/276394157-cdafd7d6-312d-45f3-9f36-a70baf5a421e.png)

Thanks a lot for all that detailed information. I already did it that way to solve the issue and it's partially working, but even using loco translate there is some strings that can't be translated.

**Comment by glaubersilva** [comment]
Hi @fidoboy 

Glad to know my last reply was useful. About the other strings, I noticed that you highlighted in your screenshots some texts related to placeholders, labels, and section titles/descriptions. These strings/texts can be customized directly in the Form Builder as you can check in the attached screenshot.

![image](https://github.com/impress-org/givewp/assets/16308864/2a650a47-f7b7-4e62-89b8-f75428896ccf)

**Comment by fidoboy** [comment]
> Hi @fidoboy
> 
> Glad to know my last reply was useful. About the other strings, I noticed that you highlighted in your screenshots some texts related to placeholders, labels, and section titles/descriptions. These strings/texts can be customized directly in the Form Builder as you can check in the attached screenshot.
> 
> ![image](https://user-images.githubusercontent.com/16308864/276606886-2a650a47-f7b7-4e62-89b8-f75428896ccf.png)

Thanks again. I've noticed that some strings can be translated from the editor also. However it could be nice if they was already translated by default from the begining. 

Also I can't find a way to translate the string being displayed when a field if left empty or it has a wrong value in frontend form. And the string "Or pay with credit card", "Cardholder name" and "MM/YYYY" can't be translated in frontend.

**Comment by glaubersilva** [comment]
Thanks for the feedback. 

About these points:

> However it could be nice if they was already translated by default from the begining to avoid end user confusions.

> Also I can't find a way to translate the string being displayed when a field if left empty or it has a wrong value in frontend form. And the string "Or pay with credit card", "Cardholder name" and "MM/YYYY" can't be translated in frontend.

We are working to make the translations for these strings be possible in the next Give version.
